use anyhow::Ok;
use std::io::Write as _;

/// Characters that must be percent-encoded in QDirStat paths.
/// Per the spec: \x00-\x20 and %
const QDIRSTAT_ENCODE_SET: &percent_encoding::AsciiSet = &percent_encoding::CONTROLS
    .add(b' ')
    .add(b'%')
    .add(b'\t')
    .add(b'\n')
    .add(b'\r');

/// Return the block-device name (e.g. `/dev/sda1`) that backs `path` by
/// invoking `df`. Falls back to `"<unknown>"` on any error or unexpected output.
fn get_device_name(path: &std::path::Path) -> String {
    std::process::Command::new("df")
        .arg(path)
        .output()
        .ok()
        .and_then(|out| {
            let stdout = String::from_utf8_lossy(&out.stdout).into_owned();
            let mut lines = stdout.lines();
            lines.next(); // skip header line
            lines.next()
                .and_then(|line| line.split_whitespace().next())
                .map(|s| s.to_string())
        })
        .unwrap_or_else(|| "<unknown>".to_string())
}

/// Write the QDirStat V2.0 cache file header.
fn write_cache_header(out: &mut dyn std::io::Write) -> std::io::Result<()> {
    let started_at = chrono::Utc::now().to_rfc3339();
    writeln!(out, "[qdirstat 2.0 cache file]")?;
    writeln!(out, "# See: https://github.com/shundhammer/qdirstat/blob/master/doc/cache-file-format.txt")?;
    writeln!(out, "# Generated by fs-delta-tracker")?;
    writeln!(out, "# Started at: {}", started_at)?;
    writeln!(out, "# Do not edit!")?;
    writeln!(out, "#")?;
    writeln!(
        out,
        "# Type\tpath\tsize\tuid\tgid\tperm.\tmtime\t<optional fields>"
    )?;
    writeln!(out)?;
    std::io::Result::Ok(())
}

/// Walk the directory in parallel, writing a QDirStat V2.0 cache file.
#[tracing::instrument(skip(output_cache_file, data_root, progress_log_interval, num_threads))]
pub async fn walk_directory(
    data_root: std::path::PathBuf,
    progress_log_interval: u64,
    output_cache_file: std::path::PathBuf,
    num_threads: usize,
    fingerprint: bool,
    compress: bool,
    cross_filesystems: bool,
    ignore_dir_size: bool,
) -> anyhow::Result<std::collections::HashMap<String, String>> {
    // 1) channel
    // Bounded with backpressure: walker threads block when the writer falls behind,
    // 64 k entries × ~256 bytes avg ≈ 16 MB peak working set.
    let (tx, rx) = crossbeam_channel::bounded::<String>(64_000);
    let (stop_tx, stop_rx) = crossbeam_channel::bounded::<()>(0);

    // 2) progress / done flags
    let counter = std::sync::Arc::new(std::sync::atomic::AtomicU64::new(0));
    let done = std::sync::Arc::new(std::sync::atomic::AtomicBool::new(false));

    // 3) writer thread
    let writer_handle = {
        let rx = rx;
        let output_path = output_cache_file.clone();
        std::thread::spawn(move || -> anyhow::Result<()> {
            if let Some(p) = output_path.parent() {
                std::fs::create_dir_all(p).map_err(|e| {
                    tracing::error!("Failed to create output directory {:?}: {}", p, e);
                    e
                })?;
            }
            let f = std::fs::File::create(&output_path).map_err(|e| {
                tracing::error!("Failed to create output file {:?}: {}", output_path, e);
                e
            })?;

            if compress {
                let mut out = std::io::BufWriter::new(flate2::write::GzEncoder::new(
                    f,
                    flate2::Compression::default(),
                ));
                write_cache_header(&mut out).map_err(|e| {
                    tracing::error!("Failed to write cache header to {:?}: {}", output_path, e);
                    e
                })?;
                for line in rx {
                    out.write_all(line.as_bytes()).map_err(|e| {
                        tracing::error!("Failed to write to {:?}: {}", output_path, e);
                        e
                    })?;
                }
                out.into_inner()
                    .map_err(|e| {
                        tracing::error!("Failed to flush BufWriter before finishing gzip for {:?}: {}", output_path, e.error());
                        std::io::Error::new(e.error().kind(), format!("{}", e.error()))
                    })?
                    .finish()
                    .map_err(|e| {
                        tracing::error!("Failed to finish gzip encoding for {:?}: {}", output_path, e);
                        e
                    })?;
            } else {
                let mut out = std::io::BufWriter::new(f);
                write_cache_header(&mut out).map_err(|e| {
                    tracing::error!("Failed to write cache header to {:?}: {}", output_path, e);
                    e
                })?;
                for line in rx {
                    out.write_all(line.as_bytes()).map_err(|e| {
                        tracing::error!("Failed to write to {:?}: {}", output_path, e);
                        e
                    })?;
                }
                out.flush().map_err(|e| {
                    tracing::error!("Failed to flush {:?}: {}", output_path, e);
                    e
                })?;
            }
            Ok(())
        })
    };

    // 4) progress thread
    let progress_handle = {
        let counter = counter.clone();
        let ticker =
            crossbeam_channel::tick(std::time::Duration::from_secs(progress_log_interval));
        std::thread::spawn(move || {
            let start = std::time::Instant::now();
            let mut last_cnt = 0;
            let mut last_t = start;

            loop {
                crossbeam_channel::select! {
                    recv(stop_rx) -> _ => {
                        break;
                    },
                    recv(ticker) -> _ => {
                        let now = std::time::Instant::now();
                        let total = counter.load(std::sync::atomic::Ordering::Relaxed);
                        let interval_secs = now.duration_since(last_t).as_secs_f64().max(1e-9);
                        let interval_cnt  = total - last_cnt;
                        let rate_now = interval_cnt as f64 / interval_secs;
                        let total_secs = now.duration_since(start).as_secs();
                        let rate_all = total as f64 / total_secs as f64;
                        let hh = total_secs / 3600;
                        let mm = (total_secs % 3600) / 60;
                        let ss = total_secs % 60;

                        tracing::info!(
                            "📊 Progress: {} entries in {:02}:{:02}:{:02}, {:.1} e/s (last {}s), {:.1} e/s (overall)",
                            total, hh, mm, ss,
                            rate_now, progress_log_interval, rate_all
                        );

                        last_cnt = total;
                        last_t = now;
                    }
                }
            }
        })
    };

    // 5) do the blocking parallel walk
    let tx2 = tx.clone();
    let counter2 = counter.clone();
    let done2 = done.clone();
    let root = data_root.clone();

    let start = std::time::Instant::now();
    tracing::debug!("🔍 Starting directory walk in parallel...");

    tokio::task::spawn_blocking(move || {
        use std::os::unix::fs::MetadataExt;
        use std::os::unix::fs::FileTypeExt;
        use std::os::unix::ffi::OsStrExt;

        let mut builder = ignore::WalkBuilder::new(root);
        builder.ignore(false).hidden(false).git_ignore(false);
        builder.same_file_system(!cross_filesystems);
        builder.threads(num_threads);

        builder.build_parallel().run(|| {
            let tx = tx2.clone();
            let cnt = counter2.clone();
            Box::new(move |res| {
                let ent = match res {
                    Err(e) => {
                        // tracing::warn!("Skipped entry: {}", e);
                        let _ = tx.send(format!("# skipped: {}\n", e));
                        return ignore::WalkState::Continue;
                    }
                    std::result::Result::Ok(e) => e,
                };

                let ft = match ent.file_type() {
                    Some(ft) => ft,
                    None => {
                        let path_str = ent.path().display().to_string();
                        tracing::warn!("Could not determine file type for {}", path_str);
                        let _ = tx.send(format!(
                            "# skipped: {} - could not determine file type\n",
                            path_str
                        ));
                        return ignore::WalkState::Continue;
                    }
                };

                let meta = match ent.metadata() {
                    std::result::Result::Ok(m) => m,
                    Err(e) => {
                        let path_str = ent.path().display().to_string();
                        tracing::warn!("Metadata error for {}: {}", path_str, e);
                        let _ = tx.send(format!("# skipped: {} - {}\n", path_str, e));
                        return ignore::WalkState::Continue;
                    }
                };

                // Determine entry type
                let type_char = if ft.is_file() {
                    "F"
                } else if ft.is_dir() {
                    "D"
                } else if ft.is_symlink() {
                    "L"
                } else if ft.is_block_device() {
                    "BlockDev"
                } else if ft.is_char_device() {
                    "CharDev"
                } else if ft.is_fifo() {
                    "FIFO"
                } else if ft.is_socket() {
                    "Socket"
                } else {
                    return ignore::WalkState::Continue;
                };

                // Byte-level percent-encoding: preserves non-UTF-8 byte
                // sequences from the OS (Latin-1, Shift-JIS, etc.) faithfully,
                // matching what readdir() returns and what the Perl script writes.
                let encoded_path = percent_encoding::percent_encode(
                    ent.path().as_os_str().as_bytes(),
                    QDIRSTAT_ENCODE_SET,
                )
                .to_string();

                let size = meta.len();
                let uid = meta.uid();
                let gid = meta.gid();
                // Extract only permission bits (lower 12 bits)
                let perm = meta.mode() & 0o7777;
                let nlink = meta.nlink();
                let blocks = meta.blocks();
                // Zero directory size when --ignore-dir-size is set.
                // Useful for CephFS and similar filesystems that report
                // the subtree total as the directory inode's own size.
                let effective_size = if ft.is_dir() && ignore_dir_size { 0u64 } else { size };

                let mtime_secs = meta
                    .modified()
                    .ok()
                    .and_then(|t| t.duration_since(std::time::UNIX_EPOCH).ok())
                    .map(|d| d.as_secs() as i64)
                    .unwrap_or(0);

                // Build optional suffix fields.
                // Directories don't get blocks: or links: per the QDirStat spec.
                let mut optional = String::new();
                if !ft.is_dir() {
                    // blocks: only for sparse files (allocated < apparent size).
                    // Guard blocks > 0: a zero-block file with size > 0 is valid
                    // on some filesystems and must not be flagged as sparse.
                    if blocks > 0 && blocks * 512 < size {
                        optional.push_str(&format!("\tblocks: {}", blocks));
                    }
                    // links: only when hard-link count > 1
                    if nlink > 1 {
                        optional.push_str(&format!("\tlinks: {}", nlink));
                    }
                }

                // fingerprint: for regular files only; failures are silently skipped
                // (no comment emitted – a missing fingerprint is not a skipped entry).
                //
                // NOTE: `fingerprint:` is a non-standard extension field beyond the two optional
                // fields defined by the QDirStat V2.0 spec (`blocks:`, `links:`). Current QDirStat
                // silently tolerates unknown trailing tokens, but strict or third-party parsers
                // may reject or warn on this field. It carries no meaning within QDirStat itself
                // and exists solely for the broader fs-delta-tracker change-detection pipeline.
                if ft.is_file() && fingerprint {
                    if let std::result::Result::Ok(fp) = crate::fingerprint::compute_fingerprint_default(ent.path()) {
                        if !fp.is_empty() {
                            optional.push_str(&format!("\tfingerprint: {}", fp));
                        }
                    }
                }

                let line = format!(
                    "{}\t{}\t{}\t{}\t{}\t0{:04o}\t0x{:x}{}\n",
                    type_char,
                    encoded_path,
                    effective_size,
                    uid,
                    gid,
                    perm,
                    mtime_secs,
                    optional,
                );

                cnt.fetch_add(1, std::sync::atomic::Ordering::Relaxed);

                if ent.depth() == 0 && ft.is_dir() {
                    let device_name = get_device_name(ent.path());
                    let _ = tx.send(format!("{}# Device: {}\n\n", line, device_name));
                } else {
                    let _ = tx.send(line);
                }
                ignore::WalkState::Continue
            })
        });

        // done walking
        drop(tx2);
        done2.store(true, std::sync::atomic::Ordering::Relaxed);
    })
    .await?;

    // Write a footer comment before closing the channel so the file always
    // contains a record of how the crawler ended.
    tracing::debug!("📂 Directory walk completed, writing footer...");
    let total_entries = counter.load(std::sync::atomic::Ordering::Relaxed);
    let timestamp = chrono::Utc::now().to_rfc3339();
    let footer = format!(
        "\n\
        # --- fs-delta-tracker crawler footer ---\n\
        # Status: COMPLETED\n\
        # Total entries: {}\n\
        # Timestamp: {}\n\
        # --- fs-delta-tracker crawler footer ---\n",
        total_entries, timestamp,
    );
    let _ = tx.send(footer);
    // drop the original TX here so that the writer thread sees EOF
    drop(tx);

    // signal the progress thread to stop
    tracing::debug!("\u{1f51a} Signaling progress thread to stop...");
    done.store(true, std::sync::atomic::Ordering::Relaxed);
    let _ = stop_tx.send(());

    // 6) wait for both threads to finish
    tracing::debug!("⏳ Waiting for progress and writer threads to finish...");
    let _ = progress_handle.join();
    writer_handle
        .join()
        .map_err(|e| anyhow::anyhow!("Writer thread panicked: {:?}", e))??;

    // 7) final stats
    let total = counter.load(std::sync::atomic::Ordering::Relaxed) as f64;
    let elapsed = std::time::Instant::now()
        .duration_since(start)
        .as_secs_f64();
    tracing::info!(
        "📊 Final stats: {} entries in {:.1}s ({:.1} e/s)",
        total as u64,
        elapsed,
        total / elapsed
    );

    let mut metadata = std::collections::HashMap::new();
    metadata.insert(
        "data_root".to_string(),
        data_root.to_string_lossy().to_string(),
    );
    metadata.insert("crawl_timer_duration_s".to_string(), elapsed.to_string());
    metadata.insert("total_entries_processed".to_string(), (total as u64).to_string());
    metadata.insert(
        "crawler_entries_per_second".to_string(),
        (total / elapsed).to_string(),
    );

    Ok(metadata)
}
