use anyhow::Ok;
use std::io::Write as _;

/// Characters that must be percent-encoded in QDirStat paths.
/// Per the spec: \x00-\x20 and %
const QDIRSTAT_ENCODE_SET: &percent_encoding::AsciiSet = &percent_encoding::CONTROLS
    .add(b' ')
    .add(b'%')
    .add(b'\t')
    .add(b'\n')
    .add(b'\r');

/// Write the QDirStat V2.0 cache file header.
fn write_cache_header(out: &mut dyn std::io::Write) -> std::io::Result<()> {
    writeln!(out, "[qdirstat 2.0 cache file]")?;
    writeln!(out, "# Generated by fs-delta-tracker")?;
    writeln!(out, "# Do not edit!")?;
    writeln!(out, "#")?;
    writeln!(
        out,
        "# Type\tpath\tsize\tuid\tgid\tperm.\tmtime\t<optional fields>"
    )?;
    writeln!(out)?;
    std::io::Result::Ok(())
}

/// Walk the directory in parallel, writing a QDirStat V2.0 cache file.
#[tracing::instrument(skip(output_cache_file, data_root, progress_log_interval, num_threads))]
pub async fn walk_directory(
    data_root: std::path::PathBuf,
    progress_log_interval: u64,
    scan_id: i32,
    output_cache_file: std::path::PathBuf,
    num_threads: usize,
) -> anyhow::Result<std::collections::HashMap<String, String>> {
    // 1) channel
    let (tx, rx) = crossbeam_channel::unbounded::<String>();
    let (stop_tx, stop_rx) = crossbeam_channel::bounded::<()>(0);

    // 2) progress / done flags
    let counter = std::sync::Arc::new(std::sync::atomic::AtomicU64::new(0));
    let done = std::sync::Arc::new(std::sync::atomic::AtomicBool::new(false));

    // 3) writer thread
    let writer_handle = {
        let rx = rx;
        let output_path = output_cache_file.clone();
        std::thread::spawn(move || {
            if let Some(p) = output_path.parent() {
                std::fs::create_dir_all(p).unwrap();
            }
            let f = std::fs::File::create(&output_path).unwrap();
            let mut out = std::io::BufWriter::new(f);

            // Write QDirStat header
            write_cache_header(&mut out).unwrap();

            for line in rx {
                let _ = out.write_all(line.as_bytes());
            }
            let _ = out.flush();
        })
    };

    // 4) progress thread
    let progress_handle = {
        let counter = counter.clone();
        let ticker =
            crossbeam_channel::tick(std::time::Duration::from_secs(progress_log_interval));
        std::thread::spawn(move || {
            let start = std::time::Instant::now();
            let mut last_cnt = 0;
            let mut last_t = start;

            loop {
                crossbeam_channel::select! {
                    recv(stop_rx) -> _ => {
                        break;
                    },
                    recv(ticker) -> _ => {
                        let now = std::time::Instant::now();
                        let total = counter.load(std::sync::atomic::Ordering::Relaxed);
                        let interval_secs = now.duration_since(last_t).as_secs_f64().max(1e-9);
                        let interval_cnt  = total - last_cnt;
                        let rate_now = interval_cnt as f64 / interval_secs;
                        let total_secs = now.duration_since(start).as_secs();
                        let rate_all = total as f64 / total_secs as f64;
                        let hh = total_secs / 3600;
                        let mm = (total_secs % 3600) / 60;
                        let ss = total_secs % 60;

                        tracing::info!(
                            "📊 Progress: {} entries in {:02}:{:02}:{:02}, {:.1} e/s (last {}s), {:.1} e/s (overall)",
                            total, hh, mm, ss,
                            rate_now, progress_log_interval, rate_all
                        );

                        last_cnt = total;
                        last_t = now;
                    }
                }
            }
        })
    };

    // 5) do the blocking parallel walk
    let tx2 = tx.clone();
    let counter2 = counter.clone();
    let done2 = done.clone();
    let root = data_root.clone();

    let start = std::time::Instant::now();
    tracing::debug!("🔍 Starting directory walk in parallel...");

    tokio::task::spawn_blocking(move || {
        use std::os::unix::fs::MetadataExt;

        let mut builder = ignore::WalkBuilder::new(root);
        builder.ignore(false).hidden(false).git_ignore(false);
        builder.same_file_system(true);
        builder.threads(num_threads);

        builder.build_parallel().run(|| {
            let tx = tx2.clone();
            let cnt = counter2.clone();
            Box::new(move |res| {
                if let std::result::Result::Ok(ent) = res {
                    if let Some(ft) = ent.file_type() {
                        if let std::result::Result::Ok(meta) = ent.metadata() {
                            // Determine entry type
                            let type_char = if ft.is_file() {
                                "F"
                            } else if ft.is_dir() {
                                "D"
                            } else if ft.is_symlink() {
                                "L"
                            } else {
                                // Skip special files (BlockDev, CharDev, FIFO, Socket)
                                return ignore::WalkState::Continue;
                            };

                            // Absolute path, percent-encoded per QDirStat spec
                            let raw_path = ent.path().to_string_lossy();
                            let encoded_path = percent_encoding::utf8_percent_encode(
                                &raw_path,
                                QDIRSTAT_ENCODE_SET,
                            )
                            .to_string();

                            let size = meta.len();
                            let uid = meta.uid();
                            let gid = meta.gid();
                            // Extract only permission bits (lower 12 bits)
                            let perm = meta.mode() & 0o7777;
                            let nlink = meta.nlink();
                            let blocks = meta.blocks();

                            let mtime_secs = meta
                                .modified()
                                .ok()
                                .and_then(|t| {
                                    t.duration_since(std::time::UNIX_EPOCH).ok()
                                })
                                .map(|d| d.as_secs() as i64)
                                .unwrap_or(0);

                            // Build optional suffix fields.
                            // Directories don't get blocks: or links: per the QDirStat spec.
                            let mut optional = String::new();
                            if !ft.is_dir() {
                                // blocks: only for sparse files (allocated < apparent size)
                                if blocks * 512 < size {
                                    optional.push_str(&format!("\tblocks: {}", blocks));
                                }
                                // links: only when hard-link count > 1
                                if nlink > 1 {
                                    optional.push_str(&format!("\tlinks: {}", nlink));
                                }
                            }

                            // fingerprint: for regular files only
                            if ft.is_file() {
                                let fingerprint =
                                    crate::fingerprint::compute_fingerprint_default(ent.path())
                                        .unwrap_or_else(|e| {
                                            tracing::warn!(
                                                "Failed to compute fingerprint for {}: {}",
                                                ent.path().display(),
                                                e
                                            );
                                            String::new()
                                        });
                                if !fingerprint.is_empty() {
                                    optional.push_str(&format!("\tfingerprint: {}", fingerprint));
                                }
                            }

                            let line = format!(
                                "{}\t{}\t{}\t{}\t{}\t{:04o}\t0x{:x}{}\n",
                                type_char,
                                encoded_path,
                                size,
                                uid,
                                gid,
                                perm,
                                mtime_secs,
                                optional,
                            );

                            cnt.fetch_add(1, std::sync::atomic::Ordering::Relaxed);
                            let _ = tx.send(line);
                        }
                    }
                }
                ignore::WalkState::Continue
            })
        });

        // done walking
        drop(tx2);
        done2.store(true, std::sync::atomic::Ordering::Relaxed);
    })
    .await?;

    // drop the original TX here so that the writer thread sees EOF
    tracing::debug!("📂 Directory walk completed, dropping sender...");
    drop(tx);

    // signal the progress thread to stop
    tracing::debug!("🔚 Signaling progress thread to stop...");
    done.store(true, std::sync::atomic::Ordering::Relaxed);
    let _ = stop_tx.send(());

    // 6) wait for both threads to finish
    tracing::debug!("⏳ Waiting for progress and writer threads to finish...");
    let _ = progress_handle.join();
    let _ = writer_handle.join();

    // 7) final stats
    let total = counter.load(std::sync::atomic::Ordering::Relaxed) as f64;
    let elapsed = std::time::Instant::now()
        .duration_since(start)
        .as_secs_f64();
    tracing::info!(
        "📊 Final stats: {} entries in {:.1}s ({:.1} e/s)",
        total as u64,
        elapsed,
        total / elapsed
    );

    let mut metadata = std::collections::HashMap::new();
    metadata.insert(
        "data_root".to_string(),
        data_root.to_string_lossy().to_string(),
    );
    metadata.insert("crawl_timer_duration_s".to_string(), elapsed.to_string());
    metadata.insert("total_entries_processed".to_string(), (total as u64).to_string());
    metadata.insert(
        "crawler_entries_per_second".to_string(),
        (total / elapsed).to_string(),
    );

    Ok(metadata)
}
